name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+38

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^8.0.0
  http: ^1.5.0
  flutter_svg: ^2.2.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  app_links: ^6.4.0
  archive: ^4.0.9
  file_picker: ^10.3.3
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/creative/
    - assets/data/creative/styles/
    - assets/data/scenes/
    - assets/characters/ceo/profile.json
    - assets/characters/ceo/references/
    - assets/templates/tiktok/
    - assets/data/processed/
    - assets/config/version.json
    - assets/branding/
    - assets/data/categories/
    - assets/data/categories/Beauty/
    - assets/data/categories/Fashion_Accessories/
    - assets/data/categories/Food_and_Beverages/
    - assets/data/categories/Health/
    - assets/data/categories/Home_and_Living/
    - assets/data/categories/Home_Appliances/
    - assets/data/categories/Men_Clothes/
    - assets/data/categories/Mobile_and_Gadgets/
    - assets/data/categories/Pets/
    - assets/data/categories/Sports_and_Outdoors/
    - assets/data/categories/Stationery/
    - assets/data/categories/Women_Clothes/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/logo_symbol.png
  adaptive_icon_background: "#0D0C0F"
  adaptive_icon_foreground: assets/branding/logo_symbol.png
