-- Supabase persistence for the private SoloForge Idea Inbox.
-- Run with the Supabase migration workflow before registering the Telegram webhook.

create table if not exists public.idea_flow_ideas (
    id bigint generated by default as identity primary key,
    title text not null check (length(btrim(title)) > 0),
    body text not null check (length(btrim(body)) > 0),
    source text not null default 'manual',
    status text not null default 'CAPTURED' check (status in (
        'CAPTURED','TRIAGED','RESEARCHED','EVALUATED','GRADUATED',
        'PARKED','REJECTED','EXPERIMENT','VALIDATED','KILLED'
    )),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.idea_flow_events (
    id bigint generated by default as identity primary key,
    idea_id bigint not null references public.idea_flow_ideas(id) on delete cascade,
    event_type text not null,
    from_status text,
    to_status text,
    actor text not null,
    reason text,
    metadata jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.idea_flow_notes (
    id bigint generated by default as identity primary key,
    idea_id bigint not null references public.idea_flow_ideas(id) on delete cascade,
    note_type text not null,
    body text not null check (length(btrim(body)) > 0),
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.idea_flow_evaluations (
    id bigint generated by default as identity primary key,
    idea_id bigint not null references public.idea_flow_ideas(id) on delete cascade,
    demand integer not null check (demand between 0 and 5),
    feasibility integer not null check (feasibility between 0 and 5),
    strategic_fit integer not null check (strategic_fit between 0 and 5),
    weighted_score numeric(3,2) not null check (weighted_score between 0 and 5),
    signal text not null check (signal in ('GRADUATE_CANDIDATE','PARK_OR_REVIEW','REJECT_CANDIDATE')),
    notes text,
    evaluator text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.idea_flow_telegram_updates (
    update_id bigint primary key,
    received_at timestamptz not null default timezone('utc', now())
);

create index if not exists idea_flow_events_idea_id_idx
    on public.idea_flow_events(idea_id, id);
create index if not exists idea_flow_evaluations_idea_id_idx
    on public.idea_flow_evaluations(idea_id, id desc);
create index if not exists idea_flow_ideas_status_idx
    on public.idea_flow_ideas(status, id desc);

alter table public.idea_flow_ideas enable row level security;
alter table public.idea_flow_events enable row level security;
alter table public.idea_flow_notes enable row level security;
alter table public.idea_flow_evaluations enable row level security;
alter table public.idea_flow_telegram_updates enable row level security;

create or replace function public.idea_flow_claim_telegram_update(p_update_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    insert into public.idea_flow_telegram_updates(update_id)
    values (p_update_id)
    on conflict do nothing;
    get diagnostics inserted_count = row_count;
    return inserted_count = 1;
end;
$$;

create or replace function public.idea_flow_capture(
    p_body text,
    p_source text,
    p_actor text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    clean_body text := btrim(p_body);
    new_id bigint;
begin
    if clean_body = '' then
        raise exception 'Idea body cannot be empty';
    end if;
    insert into public.idea_flow_ideas(title, body, source)
    values (left(btrim(split_part(clean_body, E'\n', 1)), 120), clean_body, p_source)
    returning id into new_id;
    insert into public.idea_flow_events(
        idea_id, event_type, from_status, to_status, actor, reason
    ) values (new_id, 'CAPTURED', null, 'CAPTURED', p_actor, 'idea captured');
    return new_id;
end;
$$;

create or replace function public.idea_flow_transition(
    p_idea_id bigint,
    p_to_status text,
    p_actor text,
    p_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    from_state text;
    valid_transition boolean;
begin
    select status into from_state
    from public.idea_flow_ideas where id = p_idea_id for update;
    if from_state is null then
        raise exception 'Idea not found';
    end if;

    valid_transition := case from_state
        when 'CAPTURED' then p_to_status in ('TRIAGED','PARKED','REJECTED')
        when 'TRIAGED' then p_to_status in ('RESEARCHED','EVALUATED','PARKED','REJECTED')
        when 'RESEARCHED' then p_to_status in ('EVALUATED','PARKED','REJECTED')
        when 'EVALUATED' then p_to_status in ('GRADUATED','PARKED','REJECTED')
        when 'GRADUATED' then p_to_status in ('EXPERIMENT','PARKED','KILLED')
        when 'PARKED' then p_to_status in ('TRIAGED','RESEARCHED','REJECTED')
        when 'EXPERIMENT' then p_to_status in ('VALIDATED','KILLED','PARKED')
        else false
    end;
    if not valid_transition then
        raise exception 'Invalid transition: % -> %', from_state, p_to_status;
    end if;
    if p_to_status = 'GRADUATED' and not exists (
        select 1 from public.idea_flow_evaluations where idea_id = p_idea_id
    ) then
        raise exception 'Cannot graduate without an evaluation';
    end if;

    update public.idea_flow_ideas
    set status = p_to_status, updated_at = timezone('utc', now())
    where id = p_idea_id;
    insert into public.idea_flow_events(
        idea_id, event_type, from_status, to_status, actor, reason
    ) values (
        p_idea_id, 'STATUS_CHANGED', from_state, p_to_status, p_actor,
        nullif(btrim(p_reason), '')
    );
end;
$$;

create or replace function public.idea_flow_mark_researched(
    p_idea_id bigint,
    p_research text,
    p_actor text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    clean_research text := btrim(p_research);
    current_state text;
begin
    if clean_research = '' then
        raise exception 'Research cannot be empty';
    end if;
    select status into current_state
    from public.idea_flow_ideas where id = p_idea_id for update;
    if current_state not in ('CAPTURED','TRIAGED','PARKED') then
        raise exception 'Cannot mark research from %', current_state;
    end if;
    if current_state in ('CAPTURED','PARKED') then
        update public.idea_flow_ideas set status = 'TRIAGED', updated_at = timezone('utc', now())
        where id = p_idea_id;
        insert into public.idea_flow_events(
            idea_id,event_type,from_status,to_status,actor,reason
        ) values (
            p_idea_id,'STATUS_CHANGED',current_state,'TRIAGED',p_actor,'research started'
        );
    end if;
    insert into public.idea_flow_notes(idea_id,note_type,body)
    values (p_idea_id,'RESEARCH',clean_research);
    insert into public.idea_flow_events(idea_id,event_type,actor,reason)
    values (p_idea_id,'NOTE_ADDED',p_actor,'RESEARCH');
    update public.idea_flow_ideas set status = 'RESEARCHED', updated_at = timezone('utc', now())
    where id = p_idea_id;
    insert into public.idea_flow_events(
        idea_id,event_type,from_status,to_status,actor,reason
    ) values (p_idea_id,'STATUS_CHANGED','TRIAGED','RESEARCHED',p_actor,'research recorded');
end;
$$;

create or replace function public.idea_flow_evaluate(
    p_idea_id bigint,
    p_demand integer,
    p_feasibility integer,
    p_strategic_fit integer,
    p_notes text,
    p_evaluator text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    current_state text;
    score numeric(3,2);
    score_signal text;
    evaluation_id bigint;
begin
    if p_demand is null or p_feasibility is null or p_strategic_fit is null
       or p_demand not between 0 and 5
       or p_feasibility not between 0 and 5
       or p_strategic_fit not between 0 and 5 then
        raise exception 'Scores must be integers from 0 to 5';
    end if;
    score := round((p_demand * 0.45 + p_feasibility * 0.20 + p_strategic_fit * 0.35)::numeric, 2);
    score_signal := case
        when score >= 4 then 'GRADUATE_CANDIDATE'
        when score >= 3 then 'PARK_OR_REVIEW'
        else 'REJECT_CANDIDATE'
    end;
    select status into current_state
    from public.idea_flow_ideas where id = p_idea_id for update;
    if current_state not in ('CAPTURED','TRIAGED','RESEARCHED','PARKED') then
        raise exception 'Cannot evaluate idea in status %', current_state;
    end if;
    if current_state in ('CAPTURED','PARKED') then
        update public.idea_flow_ideas set status='TRIAGED', updated_at=timezone('utc', now())
        where id=p_idea_id;
        insert into public.idea_flow_events(
            idea_id,event_type,from_status,to_status,actor,reason
        ) values (p_idea_id,'STATUS_CHANGED',current_state,'TRIAGED',p_evaluator,'evaluation started');
        current_state := 'TRIAGED';
    end if;
    insert into public.idea_flow_evaluations(
        idea_id,demand,feasibility,strategic_fit,weighted_score,signal,notes,evaluator
    ) values (
        p_idea_id,p_demand,p_feasibility,p_strategic_fit,score,score_signal,
        nullif(btrim(p_notes),''),p_evaluator
    ) returning id into evaluation_id;
    insert into public.idea_flow_events(idea_id,event_type,actor,reason,metadata)
    values (
        p_idea_id,'EVALUATED',p_evaluator,score_signal,
        jsonb_build_object('evaluation_id',evaluation_id,'weighted_score',score)
    );
    update public.idea_flow_ideas set status='EVALUATED', updated_at=timezone('utc', now())
    where id=p_idea_id;
    insert into public.idea_flow_events(
        idea_id,event_type,from_status,to_status,actor,reason
    ) values (
        p_idea_id,'STATUS_CHANGED',current_state,'EVALUATED',p_evaluator,
        'score=' || score || '; signal=' || score_signal
    );
    return jsonb_build_object(
        'evaluation_id',evaluation_id,'weighted_score',score,'signal',score_signal
    );
end;
$$;

revoke all on function public.idea_flow_claim_telegram_update(bigint) from public, anon, authenticated;
revoke all on function public.idea_flow_capture(text,text,text) from public, anon, authenticated;
revoke all on function public.idea_flow_transition(bigint,text,text,text) from public, anon, authenticated;
revoke all on function public.idea_flow_mark_researched(bigint,text,text) from public, anon, authenticated;
revoke all on function public.idea_flow_evaluate(bigint,integer,integer,integer,text,text) from public, anon, authenticated;

grant execute on function public.idea_flow_claim_telegram_update(bigint) to service_role;
grant execute on function public.idea_flow_capture(text,text,text) to service_role;
grant execute on function public.idea_flow_transition(bigint,text,text,text) to service_role;
grant execute on function public.idea_flow_mark_researched(bigint,text,text) to service_role;
grant execute on function public.idea_flow_evaluate(bigint,integer,integer,integer,text,text) to service_role;
