-- SoloForge Ops Bot v0.1 durable notification outbox.

create table if not exists public.ops_notifications (
    id bigint generated by default as identity primary key,
    event_key text not null unique,
    category text not null check (category in ('GIT','CI','DEP','SMK')),
    event_type text not null,
    severity text not null check (severity in ('info','warning','error')),
    source text not null,
    subject text not null,
    commit_sha text,
    status_label text not null,
    details jsonb not null default '{}'::jsonb,
    delivery_status text not null default 'PENDING'
        check (delivery_status in ('PENDING','SENDING','SENT','FAILED')),
    attempts integer not null default 0 check (attempts >= 0),
    last_error text,
    locked_until timestamptz,
    delivered_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.ops_notifications enable row level security;

revoke all on table public.ops_notifications from public, anon, authenticated;
grant all on table public.ops_notifications to service_role;
grant usage, select on sequence public.ops_notifications_id_seq to service_role;

create or replace function public.ops_enqueue_notification(
    p_event_key text,
    p_category text,
    p_event_type text,
    p_severity text,
    p_source text,
    p_subject text,
    p_commit_sha text,
    p_status_label text,
    p_details jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    row_value public.ops_notifications%rowtype;
begin
    insert into public.ops_notifications(
        event_key, category, event_type, severity, source, subject,
        commit_sha, status_label, details
    ) values (
        p_event_key, p_category, p_event_type, p_severity, p_source, p_subject,
        nullif(btrim(coalesce(p_commit_sha, '')), ''), p_status_label,
        coalesce(p_details, '{}'::jsonb)
    )
    on conflict (event_key) do nothing;

    select * into row_value
    from public.ops_notifications
    where event_key = p_event_key;

    if row_value.id is null then
        raise exception 'Ops notification enqueue failed';
    end if;

    return to_jsonb(row_value);
end;
$$;

create or replace function public.ops_claim_notification(p_notification_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    row_value public.ops_notifications%rowtype;
begin
    update public.ops_notifications
    set delivery_status = 'SENDING',
        attempts = case
            when delivery_status = 'SENDING' then attempts + 1
            else attempts
        end,
        last_error = case
            when delivery_status = 'SENDING' then 'reclaimed expired delivery lock'
            else last_error
        end,
        locked_until = timezone('utc', now()) + interval '2 minutes',
        updated_at = timezone('utc', now())
    where id = p_notification_id
      and (
          delivery_status = 'PENDING'
          or (
              delivery_status = 'SENDING'
              and locked_until is not null
              and locked_until <= timezone('utc', now())
          )
      )
    returning * into row_value;

    if row_value.id is null then
        return null;
    end if;
    return to_jsonb(row_value);
end;
$$;

create or replace function public.ops_mark_notification_sent(p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.ops_notifications
    set delivery_status = 'SENT',
        attempts = attempts + 1,
        last_error = null,
        locked_until = null,
        delivered_at = timezone('utc', now()),
        updated_at = timezone('utc', now())
    where id = p_notification_id
      and delivery_status = 'SENDING';
    if not found then
        raise exception 'Ops notification is not sending';
    end if;
end;
$$;

create or replace function public.ops_mark_notification_failed(
    p_notification_id bigint,
    p_error text,
    p_max_attempts integer default 3
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    next_attempt integer;
begin
    select attempts + 1 into next_attempt
    from public.ops_notifications
    where id = p_notification_id
      and delivery_status = 'SENDING'
    for update;

    if next_attempt is null then
        raise exception 'Ops notification is not sending';
    end if;

    update public.ops_notifications
    set delivery_status = case when next_attempt >= p_max_attempts then 'FAILED' else 'PENDING' end,
        attempts = next_attempt,
        last_error = left(coalesce(p_error, 'delivery error'), 500),
        locked_until = null,
        updated_at = timezone('utc', now())
    where id = p_notification_id
      and delivery_status = 'SENDING';
end;
$$;

revoke all on function public.ops_enqueue_notification(text,text,text,text,text,text,text,text,jsonb) from public, anon, authenticated;
revoke all on function public.ops_claim_notification(bigint) from public, anon, authenticated;
revoke all on function public.ops_mark_notification_sent(bigint) from public, anon, authenticated;
revoke all on function public.ops_mark_notification_failed(bigint,text,integer) from public, anon, authenticated;

grant execute on function public.ops_enqueue_notification(text,text,text,text,text,text,text,text,jsonb) to service_role;
grant execute on function public.ops_claim_notification(bigint) to service_role;
grant execute on function public.ops_mark_notification_sent(bigint) to service_role;
grant execute on function public.ops_mark_notification_failed(bigint,text,integer) to service_role;
