-- Sprint 5A: content observability, lifecycle history, and performance foundation.

create table if not exists public.content_job_events (
    id bigint generated by default as identity primary key,
    content_job_id uuid not null references public.content_jobs(id) on delete cascade,
    event_type text not null,
    from_status text,
    to_status text,
    actor text not null default 'system',
    metadata jsonb not null default '{}'::jsonb,
    occurred_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists content_job_events_job_time_idx
    on public.content_job_events (content_job_id, occurred_at desc);

alter table public.content_job_events enable row level security;

create table if not exists public.content_performance_snapshots (
    id bigint generated by default as identity primary key,
    content_job_id uuid not null references public.content_jobs(id) on delete cascade,
    platform text not null,
    publora_post_id text,
    platform_post_id text,
    source text not null default 'manual',
    views bigint,
    impressions bigint,
    reach bigint,
    reactions bigint,
    comments bigint,
    shares bigint,
    saves bigint,
    clicks bigint,
    watch_time_seconds numeric,
    metadata jsonb not null default '{}'::jsonb,
    observed_at timestamptz not null default timezone('utc'::text, now()),
    created_at timestamptz not null default timezone('utc'::text, now()),
    check (source in ('manual','publora','platform_api','import'))
);

create index if not exists content_performance_snapshots_job_time_idx
    on public.content_performance_snapshots (content_job_id, observed_at desc);

create index if not exists content_performance_snapshots_platform_time_idx
    on public.content_performance_snapshots (platform, observed_at desc);

alter table public.content_performance_snapshots enable row level security;

create or replace function public.log_content_job_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if old.status is distinct from new.status then
        insert into public.content_job_events (
            content_job_id,
            event_type,
            from_status,
            to_status,
            actor,
            metadata,
            occurred_at
        )
        values (
            new.id,
            'STATUS_CHANGED',
            old.status,
            new.status,
            'system',
            jsonb_build_object(
                'publish_status', new.publish_status,
                'qa_status', new.qa_status
            ),
            timezone('utc'::text, now())
        );
    end if;
    return new;
end;
$$;

drop trigger if exists content_jobs_status_history_trigger on public.content_jobs;

create trigger content_jobs_status_history_trigger
after update of status on public.content_jobs
for each row
execute function public.log_content_job_status_change();

insert into public.content_job_events (
    content_job_id,
    event_type,
    from_status,
    to_status,
    actor,
    metadata,
    occurred_at
)
select
    cj.id,
    'BASELINE',
    null,
    cj.status,
    'migration',
    jsonb_build_object(
        'publish_status', cj.publish_status,
        'qa_status', cj.qa_status
    ),
    coalesce(cj.updated_at, cj.created_at, timezone('utc'::text, now()))
from public.content_jobs cj
where not exists (
    select 1
    from public.content_job_events e
    where e.content_job_id = cj.id
      and e.event_type = 'BASELINE'
);
