create table if not exists public.sales_leads (
    id bigint generated by default as identity primary key,
    source text not null default 'manual',
    source_ref text,
    company text,
    contact_name text,
    contact_channel text,
    need text not null,
    evidence text,
    offer text,
    score integer not null default 0 check (score between 0 and 100),
    status text not null default 'NEW' check (status in (
        'NEW','QUALIFIED','PREPARING','READY_TO_SEND','CONTACTED','REPLIED','WON','LOST','SKIPPED'
    )),
    outreach_subject text,
    outreach_body text,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists sales_leads_status_created_idx
    on public.sales_leads(status, created_at desc);

alter table public.sales_leads enable row level security;

drop policy if exists "service role manages sales leads" on public.sales_leads;
create policy "service role manages sales leads"
on public.sales_leads
for all
to service_role
using (true)
with check (true);
